[package]
name = "deepdive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"
bevy_ecs_tilemap = "0.16.0"
shadowcast = "0.8"
pathfinding = "4.14.0"
rand = "0.9.1"
noise = "0.9.0"
bevy_asset_loader = "0.23.0"
ron = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
